export const metadata = {
  title: "Hexashop | Contact Us",
  description: "Generated by Hexashop | Contact Us",
};
function Contact() {
  return (
    <div>Contact</div>
  )
}

export default Contact