import Navbar from '@/app/components/Navbar/Navbar'
import Footer from '@/app/components/Footer/Footer'
import { Geist, Geist_Mono/*,  add name for font */ } from "next/font/google";
import "./globals.css";
/* add new font
const newFont = NameofFont({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight:['400'],
});
------------ */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hexashop",
  description: "Generated by Hexashop",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <div className='container flex flex-col justify-between'>
         <Navbar />
          {children}
          <Footer />
       </div>
      </body>
    </html>
  );
}
