import Link from 'next/link'
import React from 'react'

export const metadata = {
  title: "Hexashop | Products",
  description: "Generated by Hexashop | Products",
}; 

async function getData(){
  const res= await fetch('https://dummyjson.com/products');
  if(!res.ok){
    throw new Error('Failed')
  }
  return res.json()
}

async function Products() {
  const data = await getData();
  const products = data.products;
  
  return (   
    <div className='flex flex-wrap gap-[50px] my-[50px] justify-center'>
      {products.map(product =>(
        <Link href={`products/${product.id}`} className='flex flex-col text-center justify-between items-center
         border-[1px] border-yellow-400 rounded-[5px] w-[300px] p-[5px]' 
          key={product.id}>
            <div className='h-[60%]'>
              <img
              className='h-[100%]'
              src={product.thumbnail}
              alt='prouct1'
              />
            </div>
            <div className='flex flex-col gap-[10px]'>
                <h1 className='text-xl font-bold text-yellow-400'>{product.title}</h1>
                <p className='text-[16px]'>{product.description}</p>
            </div>
        </Link>
      ))}
    </div>
  )
}

export default Products